# Generated by Django 3.0.3 on 2020-05-01 17:36

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_user_last_reset_password_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['create_time'], 'verbose_name': '用户', 'verbose_name_plural': '用户'},
        ),
        migrations.RemoveField(
            model_name='user',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='user',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.TextField(choices=[('SUPER_ADMIN', 'Super Admin'), ('NORMAL_ADMIN', 'Normal Admin'), ('USER', 'User')], default='USER'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.TextField(error_messages={'unique': '用户名已存在！'}, help_text='请保证用户名在10字以内且不出现特殊字符', max_length=20, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()]),
        ),
    ]
